
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgungstrwucdiwmgnyql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndW5nc3Ryd3VjZGl3bWdueXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTI2MDcsImV4cCI6MjA1ODIyODYwN30.vOuFNrR2IyHceeuV7MdOGyOBTPKSRSdmaTdSZb3Z3GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
